In [2]:
import urllib
import pandas as pd

# This notebook merges votes, voting_sessions and actor information

In [ ]:
with urllib.request.urlopen("https://raw.githubusercontent.com/Somon8/social_graphs_25/main/final-project/voting-data/df_votes_all_periods.csv") as response:
    df_votes = pd.read_csv(response)

with urllib.request.urlopen("https://raw.githubusercontent.com/Somon8/social_graphs_25/main/final-project/voting-data/voting_sessions_enriched.csv") as response:
    df_voting_sessions = pd.read_csv(response)

with urllib.request.urlopen("https://raw.githubusercontent.com/Somon8/social_graphs_25/main/final-project/actor-data/actor_df.csv") as response:
    df_actors = pd.read_csv(response)

In [ ]:
df_votes.head(2)

   vote_id  vote_typeid  afstemning_id  aktørid     vote_opdateringsdato
0  1481475            3           5973     1886  2021-01-28T21:27:39.627
1  1481476            1           5973     1039      2018-02-16T10:35:23

In [20]:
relevant_topics_for_joining_on_votes = ["afstemning_id", "afstemning_nummer", "afstemning_vedtaget", "Period", "primary_topic", "all_topics"]
df_voting_sessions.head(2)

,afstemning_id,afstemning_nummer,afstemning_konklusion,afstemning_vedtaget,afstemning_kommentar,afstemning_dato,afstemning_opdateringsdato,afstemning_typeid,møde_id,møde_dato,...,score_erhverv,score_finans_budget,score_arbejdsmarked_velfærd,score_immigration,score_forsvar_sikkerhed,score_udenrigs_eu,score_retspolitik,score_transport_infrastruktur,score_bolig,score_social_familie
0,1,411,"Vedtaget\n\n108 stemmer for forslaget (V, S, D...",True,NaN,NaN,2014-09-09T09:05:59.653,2,17,2014-09-09 09:00:00,...,0,0,0,0,0,0,0,0,0,0
1,2,412,"Vedtaget\n\n98 stemmer for forslaget (V, S, DF...",True,NaN,NaN,2014-09-09T09:25:05.717,1,18,2014-09-09 09:15:00,...,2,2,0,0,1,1,0,0,0,0

In [19]:
df_actors.head(2)

   aktørid        politician              party
0     1886      Jacob Buksti  Socialdemokratiet
1     1039  Lotte Bundsgaard  Socialdemokratiet

In [ ]:
votes_with_actors = df_votes.merge(df_actors, how = "left",on = "aktørid") #THIS IS GOING TO NEED AN UPDATE WITH THE CHANGING PARTIES BUT WHATEVER
votes_with_actors.head(2)

,vote_id,vote_typeid,afstemning_id,aktørid,vote_opdateringsdato,politician,party
0,1481475,3,5973,1886,2021-01-28T21:27:39.627,Jacob Buksti,Socialdemokratiet
1,1481476,1,5973,1039,2018-02-16T10:35:23,Lotte Bundsgaard,Socialdemokratiet

In [23]:
df_voting_sessions[relevant_topics_for_joining_on_votes]

,afstemning_id,afstemning_nummer,afstemning_vedtaget,Period,primary_topic,all_topics
0,1,411,True,68,NaN,[]
1,2,412,True,68,erhverv,"['skat', 'erhverv', 'finans_budget', 'forsvar_..."
2,3,1,True,68,klima_miljø,"['klima_miljø', 'uddannelse', 'retspolitik', '..."
3,4,7,True,68,arbejdsmarked_velfærd,"['finans_budget', 'arbejdsmarked_velfærd']"
4,5,412,True,68,erhverv,"['skat', 'erhverv', 'finans_budget', 'forsvar_..."
...,...,...,...,...,...,...
10301,10378,533,True,71,sundhed,"['klima_miljø', 'sundhed', 'erhverv', 'immigra..."
10302,10379,2,True,71,forsvar_sikkerhed,"['klima_miljø', 'sundhed', 'uddannelse', 'arbe..."
10303,10380,3,True,71,uddannelse,['uddannelse']
10304,10381,5,True,71,erhverv,"['sundhed', 'erhverv', 'finans_budget', 'udenr..."
10305,10382,6,True,71,immigration,"['immigration', 'retspolitik']"

In [24]:
votes_with_actors_enriched = votes_with_actors.merge(df_voting_sessions[relevant_topics_for_joining_on_votes], how = "left", on = "afstemning_id")
votes_with_actors_enriched.head(2)

,vote_id,vote_typeid,afstemning_id,aktørid,vote_opdateringsdato,politician,party,afstemning_nummer,afstemning_vedtaget,Period,primary_topic,all_topics
0,1481475,3,5973,1886,2021-01-28T21:27:39.627,Jacob Buksti,Socialdemokratiet,4,True,65,NaN,[]
1,1481476,1,5973,1039,2018-02-16T10:35:23,Lotte Bundsgaard,Socialdemokratiet,4,True,65,NaN,[]

In [25]:
votes_with_actors_enriched.to_csv("./voting-data/all_votes_enriched.csv", index = False)