In [20]:
import urllib
import pandas as pd

# This notebook enriches the df_votes
### We add topics, periods and other interesting stuff so we can build the graphs based on a specific sorting

In [21]:
with urllib.request.urlopen("https://raw.githubusercontent.com/Somon8/social_graphs_25/main/final-project/voting-data/df_votes_all_periods.csv") as response:
    df = pd.read_csv(response)

In [22]:
# Add topic
# Add period
# Add other stuff

with urllib.request.urlopen("https://raw.githubusercontent.com/Somon8/social_graphs_25/main/final-project/folketinget_votings_enriched.csv") as response:
    df_votings = pd.read_csv(response)

In [19]:
df_votings

,id_afstemning,nummer_afstemning,konklusion,vedtaget,kommentar,mødeid,typeid_afstemning,sagstrinid,opdateringsdato_afstemning,Sagstrin,...,Møde.nummer,Møde.dagsordenurl,Møde.starttidsbemærkning,Møde.offentlighedskode,Møde.dato,Møde.statusid,Møde.typeid,Møde.periodeid,Møde.opdateringsdato,Period
0,1,411,"Vedtaget\n\n108 stemmer for forslaget (V, S, D...",True,NaN,17,2,NaN,2014-09-09T09:05:59.653,NaN,...,104.0,NaN,NaN,O,2014-09-09 09:00:00,2,1,32,2014-11-12T09:08:46.54,68
1,2,412,"Vedtaget\n\n98 stemmer for forslaget (V, S, DF...",True,NaN,18,1,4849.0,2014-09-09T09:25:05.717,"{'id': 4849, 'titel': '3. behandling', 'dato':...",...,105.0,NaN,5 min. efter afslutningen af møde nr. 104,O,2014-09-09 09:15:00,2,1,32,2014-11-12T09:11:13.353,68
2,3,1,"Vedtaget\n\n59 stemmer for forslaget (S, RV, S...",True,NaN,41,3,17351.0,2018-01-24T16:46:33.99,"{'id': 17351, 'titel': 'Behandling', 'dato': '...",...,3.0,NaN,10.00,O,2012-10-04 10:00:00,2,1,31,2023-03-09T11:47:45.12,68
3,4,7,"Vedtaget\n\n72 stemmer for forslaget (S, DF, R...",True,NaN,156,1,18370.0,2018-01-25T10:25:25.64,"{'id': 18370, 'titel': '3. behandling', 'dato'...",...,15.0,NaN,Mødet starter umiddelbart efter møde 14 er slut.,O,2012-11-06 00:00:00,2,1,31,2023-03-09T11:46:27.79,68
4,5,412,"Vedtaget\n\n98 stemmer for forslaget (V, S, DF...",True,NaN,18,1,4849.0,2017-08-10T12:57:52.27,"{'id': 4849, 'titel': '3. behandling', 'dato':...",...,105.0,NaN,5 min. efter afslutningen af møde nr. 104,O,2014-09-09 09:15:00,2,1,32,2014-11-12T09:11:13.353,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10299,10376,467,"Vedtaget\nFor stemte 105 (S, V, DD, SF, LA, M,...",True,NaN,15164,3,266833.0,2025-06-11T15:00:50.97,"{'id': 266833, 'titel': 'Behandling', 'dato': ...",...,105.0,NaN,NaN,O,2025-06-11 09:00:00,2,1,163,2025-09-08T10:10:26.747,71
10300,10377,532,"Vedtaget\nFor stemte 91 (S, V, DD, SF, LA, M, ...",True,Ved en fejl blev der stemt fra Peter Juel-Jens...,14602,1,267148.0,2025-09-09T12:30:12.467,"{'id': 267148, 'titel': 'Eventuelt: 3. behandl...",...,110.0,NaN,NaN,O,2025-09-09 09:00:00,2,1,163,2025-09-10T08:47:28.683,71
10301,10378,533,"Vedtaget\nFor stemte 93 (S, V, DD, SF, LA, M, ...",True,Grundet en teknisk fejl kunne der ikke stemmes...,15399,1,267397.0,2025-09-30T14:56:15.043,"{'id': 267397, 'titel': '3. behandling', 'dato...",...,112.0,NaN,NaN,O,2025-09-30 13:00:00,2,1,163,2025-10-01T09:12:40.153,71
10302,10379,2,"Vedtaget\nFor stemte 59 (S, V, M, JF, Jeppe Sø...",True,NaN,15443,3,268868.0,2025-10-10T11:45:43.137,"{'id': 268868, 'titel': 'Behandling', 'dato': ...",...,3.0,NaN,NaN,O,2025-10-09 08:00:00,2,1,165,2025-10-10T10:51:47.74,71
10303,10380,3,"Forslaget er vedtaget\nFor stemte 56 (S, V og ...",True,NaN,15446,3,269214.0,2025-10-24T09:45:23.93,"{'id': 269214, 'titel': 'Behandling', 'dato': ...",...,6.0,NaN,NaN,O,2025-10-23 10:00:00,2,1,165,2025-10-24T09:35:56.02,71

In [23]:
relevant_cols_from_votings = ['Period', 'id_afstemning', 'vedtaget', 'Møde.dato'] #Topic etc.


#IS Møde.dato the correct date????????????????????


# We need to add theme as well
#Here we can also add what party the politician belonged to at the time

df_enriched = df.merge(df_votings[relevant_cols_from_votings], how='left', left_on='voting_id', right_on='id_afstemning')

df_enriched.drop(columns = ['id_afstemning'], inplace=True) #We just needed it for the join

In [24]:
df_enriched

,voting_id,party,politician,vote_type,Period,vedtaget,Møde.dato
0,1,Enhedslisten,Frank Aaen,1,68,True,2014-09-09 09:00:00
1,1,Socialdemokratiet,Nicolai Wammen,3,68,True,2014-09-09 09:00:00
2,1,Inuit Ataqatigiit,Sara Olsvig,3,68,True,2014-09-09 09:00:00
3,1,Socialdemokratiet,Christine Antorini,3,68,True,2014-09-09 09:00:00
4,1,Dansk Folkeparti,Alex Ahrendtsen,1,68,True,2014-09-09 09:00:00
...,...,...,...,...,...,...,...
1007695,10380,Socialistisk Folkeparti,Charlotte Broman Mølbæk,3,71,True,2025-10-23 10:00:00
1007696,10380,Socialistisk Folkeparti,Signe Munk,2,71,True,2025-10-23 10:00:00
1007697,10380,Det Konservative Folkeparti,Mona Juul,3,71,True,2025-10-23 10:00:00
1007698,10380,Socialdemokratiet,Henrik Møller,1,71,True,2025-10-23 10:00:00
1007699,10380,Socialdemokratiet,Rasmus Stoklund,1,71,True,2025-10-23 10:00:00

In [25]:
df_enriched.to_csv("./voting-data/df_votes_enriched.csv", index = False)